# Bibliotecas

In [16]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import statistics
import seaborn as sns
from scipy.stats import levene
from scipy.stats import shapiro
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import kruskal
import scikit_posthocs as sp
from scipy.stats import levene, shapiro, kruskal
import pingouin as pg

# Funções

In [17]:
# Funções auxiliares
def run_levene(df, feature, group_col='concentration'):
    groups = [df.loc[df[group_col] == c, feature] for c in df[group_col].unique()]
    stat, p = levene(*groups)
    status = "homocedasticidade" if p > 0.05 else "heterocedasticidade"
    print(f"Levene p-valor ({feature}) = {p:.4f} -> {status}")
    return p > 0.05  # True se homocedástico


def run_shapiro(df, feature, group_col='concentration'):
    normal_all = True
    for c in sorted(df[group_col].unique()):
        data = df.loc[df[group_col] == c, feature]
        stat, p = shapiro(data)
        normality = "distribuição normal" if p > 0.05 else "não normal"
        print(f"Concentração {c}: p = {p:.4f} -> {normality}")
        if p <= 0.05:
            normal_all = False
    return normal_all  # True se todos os grupos normais


def run_anova_oneway(df, feature, group_col='concentration', normal=True, homoced=True):
    if normal and homoced:
        # ANOVA clássico
        print("\n=== ANOVA One-way (clássico) ===")
        model = ols(f'{feature} ~ C({group_col})', data=df).fit()
        anova_results = anova_lm(model)
        print(anova_results)
        return "anova"

    elif normal and not homoced:
        # Welch ANOVA
        print("\n=== Welch ANOVA (heterocedasticidade) ===")
        welch = pg.welch_anova(dv=feature, between=group_col, data=df)
        print(welch)
        return "welch"

    else:
        # Kruskal-Wallis
        print("\n=== Kruskal-Wallis (não paramétrico) ===")
        groups = [df.loc[df[group_col] == c, feature] for c in df[group_col].unique()]
        stat, p = kruskal(*groups)
        print(f"estatística = {stat:.4f}, p = {p:.4f}")
        return "kruskal"


def run_posthoc(df, feature, group_col='concentration', method="anova"):
    if method == "anova":
        print("\n--- Tukey HSD ---")
        tukey = pairwise_tukeyhsd(endog=df[feature],
                                  groups=df[group_col],
                                  alpha=0.05)
        print(tukey)

    elif method == "welch":
        print("\n--- Games-Howell ---")
        gh = pg.pairwise_gameshowell(dv=feature, between=group_col, data=df)
        print(gh)

    elif method == "kruskal":
        print("\n--- Dunn test (pós-hoc não paramétrico) ---")
        dunn = sp.posthoc_dunn(df, val_col=feature, group_col=group_col, p_adjust='bonferroni')
        print(dunn)


def run_anova_twoway(df, feature, factor1='concentration', factor2='compound'):
    print("\n=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===")
    model = ols(f'{feature} ~ C({factor1}) + C({factor2}) + C({factor1}):C({factor2})', data=df).fit()
    anova_results = anova_lm(model)
    print(anova_results)

    for factor in [f"C({factor1})", f"C({factor2})", f"C({factor1}):C({factor2})"]:
        p_value = anova_results.loc[factor, 'PR(>F)']
        if p_value < 0.05:
            print(f"{factor}: efeito significativo (p = {p_value:.4f})")
        else:
            print(f"{factor}: sem efeito significativo (p = {p_value:.4f})")

# Dataset

In [18]:
df = pd.read_excel("../../bancos de dados/dataset_premium.xlsx")

controle = df[df["type"] == "Control"]

controle_BCT = controle.copy()
controle_BCT["type"] = "BCT"

controle_BST = controle.copy()
controle_BST["type"] = "BST"

df_exp = pd.concat([df, controle_BCT, controle_BST], ignore_index=True)

df_exp = df_exp[df_exp['type'] != 'Control']

df = df[0:60]

display(df)

,sample,type,concentration,bpm,body_length,yolk_sac_area,pigmented_area,open_swim_bladder,edema_present,deformation_present,aquisition_data
0,1_bct_1,BCT,1.0,115,3.721,0.396,18096,no,no,no,2025-08-18T15:35:09.206382-03:00
1,2_bct_1,BCT,1.0,133,3.933,0.432,19992,no,no,no,2025-08-18T15:41:30.4801149-03:00
2,3_bct_1,BCT,1.0,149,3.690,0.245,23613,no,no,yes,2025-08-18T15:45:05.6896737-03:00
3,4_bct_1,BCT,1.0,124,3.909,0.362,27886,no,no,no,2025-08-18T15:49:14.9293665-03:00
4,5_bct_1,BCT,1.0,124,4.302,0.501,27014,no,no,no,2025-08-18T15:56:33.7860505-03:00
5,6_bct_1,BCT,1.0,129,3.414,0.396,15959,no,yes,yes,2025-08-18T16:02:00.6964589-03:00
6,7_bct_1,BCT,1.0,148,3.707,0.349,24064,no,no,no,2025-08-18T16:08:26.0680252-03:00
7,8_bct_1,BCT,1.0,133,3.915,0.355,20781,no,yes,no,2025-08-18T16:15:37.3798923-03:00
8,9_bct_1,BCT,1.0,137,3.857,0.309,18757,no,no,yes,2025-08-18T16:22:04.9105528-03:00
9,1_bst_1,BST,1.0,119,3.901,0.239,26009,no,no,yes,2025-08-18T16:30:54.3457357-03:00
10,2_bst_1,BST,1.0,166,4.115,0.258,24912,no,no,no,2025-08-18T16:33:50.505027-03:00
11,3_bst_1,BST,1.0,138,3.962,0.278,20217,no,no,no,2025-08-18T16:37:40.2942717-03:00
12,4_bst_1,BST,1.0,151,3.754,0.346,22207,no,yes,no,2025-08-18T16:44:00.9755289-03:00
13,5_bst_1,BST,1.0,153,3.931,0.269,21153,no,yes,yes,2025-08-18T16:47:28.9780532-03:00
14,6_bst_1,BST,1.0,147,3.758,0.305,16724,no,no,no,2025-08-18T16:52:03.4167386-03:00
15,7_bst_1,BST,1.0,120,3.230,0.386,12720,no,yes,no,2025-08-18T16:57:18.880994-03:00
16,8_bst_1,BST,1.0,118,4.010,0.261,22888,no,no,no,2025-08-18T17:02:40.0099859-03:00
17,9_bst_1,BST,1.0,147,3.770,0.333,20139,no,no,yes,2025-08-18T17:04:22.5311669-03:00
18,10_bst_1,BST,1.0,147,3.876,0.376,24657,no,no,yes,2025-08-18T17:13:42.1742654-03:00
19,1_control,Control,0.0,168,3.916,0.253,11778,no,no,no,2025-08-18T17:22:38.5392426-03:00
20,2_control,Control,0.0,135,4.005,0.302,10588,yes,no,no,2025-08-18T17:28:52.5058145-03:00
21,3_control,Control,0.0,161,3.031,0.178,8301,yes,no,no,2025-08-18T17:33:45.9446081-03:00
22,4_control,Control,0.0,151,3.419,0.201,9867,yes,no,no,2025-08-18T17:38:20.2332987-03:00
23,5_control,Control,0.0,158,3.803,0.338,10089,yes,no,no,2025-08-18T17:43:41.4786-03:00
24,6_control,Control,0.0,155,3.811,0.231,11407,yes,no,no,2025-08-18T17:48:44.7663925-03:00
25,7_control,Control,0.0,170,3.614,0.223,9827,yes,no,no,2025-08-18T17:52:26.7261001-03:00
26,8_control,Control,0.0,155,3.984,0.240,12035,no,no,no,2025-08-18T17:56:05.4766248-03:00
27,9_control,Control,0.0,167,4.033,0.239,11659,no,no,no,2025-08-18T17:59:49.5457671-03:00
28,10_control,Control,0.0,157,4.025,0.273,13254,yes,no,no,2025-08-18T18:03:36.2415951-03:00
29,11_control,Control,0.0,168,3.868,0.265,10094,yes,no,no,2025-08-18T18:07:31.7124646-03:00
30,12_control,Control,0.0,158,4.096,0.236,10593,yes,no,no,2025-08-18T18:11:15.6105259-03:00
31,1_bct_2,BCT,2.0,106,3.279,0.328,18934,no,no,yes,2025-08-19T16:32:31.1586986-03:00
32,2_bct_2,BCT,2.0,120,3.613,0.363,21281,no,yes,yes,2025-08-19T16:36:37.8272593-03:00
33,3_bct_2,BCT,2.0,140,3.409,0.305,18551,no,yes,yes,2025-08-19T16:39:58.0354829-03:00
34,4_bct_2,BCT,2.0,116,3.385,0.319,15749,no,yes,yes,2025-08-19T16:43:34.8409994-03:00
35,5_bct_2,BCT,2.0,127,3.398,0.353,17547,no,yes,yes,2025-08-19T16:50:14.7964371-03:00
36,6_bct_2,BCT,2.0,113,3.426,0.344,21658,no,yes,yes,2025-08-19T16:58:41.8210842-03:00
37,7_bct_2,BCT,2.0,131,3.566,0.302,25872,no,yes,no,2025-08-19T17:01:19.0300614-03:00
38,8_bct_2,BCT,2.0,125,3.540,0.354,25088,no,yes,yes,2025-08-19T17:04:31.0801673-03:00
39,9_bct_2,BCT,2.0,132,3.384,0.356,22907,no,yes,yes,2025-08-19T17:07:40.9441888-03:00
40,10_bct_2,BCT,2.0,132,3.411,0.332,24137,no,yes,yes,2025-08-19T17:11:33.7791008-03:00
41,1_bst_2,BST,2.0,160,3.314,0.346,19507,no,yes,yes,2025-08-19T15:45:37.852954-03:00
42,2_bst_2,BST,2.0,139,3.385,0.330,12907,no,yes,yes,2025-08-19T15:53:13.3665517-03:00
43,3_bst_2,BST,2.0,126,3.420,0.283,19649,no,yes,yes,2025-08-19T15:56:17.6191758-03:00
44,4_bst_2,BST,2.0,132,3.136,0.364,18243,no,yes,yes,2025-08-19T16:02:52.4700929-03:00
45,5_bst_2,BST,2.0,145,3.458,0.315,23010,no,yes,yes,2025-08-19T16:07:15.2305069-03:00
46,6_bst_2,BST,2.0,126,3.289,0.319,19419,no,no,yes,2025-08-19T16:10:40.980017-03:00
47,7_bst_2,BST,2.0,121,3.514,0.357,29341,no,yes,yes,2025-08-19T16:17:02.7529889-03:00
48,8_bst_2,BST,2.0,119,3.404,0.291,23946,no,yes,yes,2025-08-19T16:19:40.1439484-03:00
49,9_bst_2,BST,2.0,138,3.323,0.303,19968,no,no,yes,2025-08-19T16:25:00.5970844-03:00
50,1_control,Control,0.0,150,4.109,0.256,11101,no,no,no,2025-08-19T17:17:17.1019075-03:00
51,2_control,Control,0.0,147,3.947,0.218,10884,no,no,no,2025-08-19T17:21:10.4139313-03:00
52,3_control,Control,0.0,161,3.866,0.238,17684,no,no,no,2025-08-19T17:27:26.1496872-03:00
53,4_control,Control,0.0,140,3.890,0.237,10765,no,no,no,2025-08-19T17:31:42.8639814-03:00
54,5_control,Control,0.0,153,3.937,0.270,9822,no,no,no,2025-08-19T17:36:50.2598087-03:00
55,6_control,Control,0.0,150,4.085,0.291,9437,yes,no,no,2025-08-19T17:43:08.8415359-03:00
56,7_control,Control,0.0,143,4.126,0.292,10351,no,no,no,2025-08-19T17:46:50.3386111-03:00
57,8_control,Control,0.0,148,3.867,0.266,12785,no,no,no,2025-08-19T17:50:29.5520521-03:00
58,9_control,Control,0.0,128,3.433,0.277,10602,no,no,yes,2025-08-19T17:53:25.0910725-03:00
59,10_control,Control,0.0,126,3.845,0.247,11180,yes,no,no,2025-08-19T17:57:24.2001492-03:00

# Anova

Três regras precisam ser satisfeitas:
- Independência das observações (Cada peixe é um indivíduo e não interfere nos resultados de outros)
- Homogenidade na variância
- Distribuição Normal

In [19]:
df = pd.read_excel("../../bancos de dados/dataset_premium.xlsx")

df_BCT = df[df["type"] != "BST"]
df_BST = df[df["type"] != "BCT"]

df_BCT = df_BCT.copy()
df_BST = df_BST.copy()

bct_c = []

for i in range(len(df_BCT)):
    bct_c.append('BCT')

bst_c = []

for i in range(len(df_BST)):
    bst_c.append('BST')

df_BCT['type'] = bct_c
df_BST['type'] = bst_c

display(df)

,sample,type,concentration,bpm,body_length,yolk_sac_area,pigmented_area,open_swim_bladder,edema_present,deformation_present,aquisition_data
0,1_bct_1,BCT,1.0,115,3.721,0.396,18096,no,no,no,2025-08-18T15:35:09.206382-03:00
1,2_bct_1,BCT,1.0,133,3.933,0.432,19992,no,no,no,2025-08-18T15:41:30.4801149-03:00
2,3_bct_1,BCT,1.0,149,3.690,0.245,23613,no,no,yes,2025-08-18T15:45:05.6896737-03:00
3,4_bct_1,BCT,1.0,124,3.909,0.362,27886,no,no,no,2025-08-18T15:49:14.9293665-03:00
4,5_bct_1,BCT,1.0,124,4.302,0.501,27014,no,no,no,2025-08-18T15:56:33.7860505-03:00
...,...,...,...,...,...,...,...,...,...,...,...
90,8_control,Control,0.0,152,3.849,0.266,11241,no,no,no,NaN
91,9_control,Control,0.0,172,3.971,0.326,13793,yes,no,no,NaN
92,10_control,Control,0.0,168,3.966,0.262,11152,no,no,no,NaN
93,11_control,Control,0.0,152,3.974,0.305,12402,yes,no,yes,NaN
94,12_control,Control,0.0,152,3.994,0.298,13940,yes,no,no,NaN

# Parâmetros Premium

## BPM

In [20]:
features = ['bpm']
compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)


# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: bpm

Levene p-valor (bpm) = 0.6004 -> homocedasticidade
Concentração 0.0: p = 0.2125 -> distribuição normal
Concentração 0.5: p = 0.7464 -> distribuição normal
Concentração 1.0: p = 0.6834 -> distribuição normal
Concentração 2.0: p = 0.8795 -> distribuição normal

=== ANOVA One-way (clássico) ===
                    df       sum_sq      mean_sq          F        PR(>F)
C(concentration)   3.0  9827.134746  3275.711582  26.090981  6.317112e-11
Residual          60.0  7532.974629   125.549577        NaN           NaN

--- Tukey HSD ---
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
group1 group2 meandiff p-adj   lower    upper   reject
------------------------------------------------------
   0.0    0.5 -21.3021    0.0 -31.5728 -11.0315   True
   0.0    1.0  -21.585    0.0 -32.6844 -10.4856   True
   0.0    2.0 -29.8294    0.0  -40.481 -19.1779   True
   0.5    1.0  -0.2828 0.9999 -13.5912  13.0255  False
   0.5    2.0  -8.5273 0.3116 -21.4644   4.4099  False
   1.0    2.0  -8.2444 0.3856 -21.8489     5.36  False
------------------------------------------------------

=== BST ===

Variável: bpm

Levene p-valor (bpm) = 0.5587 -> homocedasticidade
Concentração 0.0: p = 0.2125 -> distribuição normal
Concentração 0.5: p = 0.6611 -> distribuição normal
Concentração 1.0: p = 0.1517 -> distribuição normal
Concentração 2.0: p = 0.4910 -> distribuição normal

=== ANOVA One-way (clássico) ===
                    df       sum_sq      mean_sq         F    PR(>F)
C(concentration)   3.0  4544.167873  1514.722624  9.671778  0.000026
Residual          61.0  9553.370588   156.612633       NaN       NaN

--- Tukey HSD ---
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
   0.0    0.5 -16.0294 0.0018 -27.1283 -4.9305   True
   0.0    1.0 -13.4294 0.0208 -25.3204 -1.5385   True
   0.0    2.0 -20.0294 0.0004 -32.4203 -7.6385   True
   0.5    1.0      2.6 0.9621 -11.5531 16.7531  False
   0.5    2.0     -4.0 0.8868 -18.5756 10.5756  False
   1.0    2.0     -6.6 0.6616 -21.7875  8.5875  False
-----------------------------------------------------

=== ANOVA Two-way: bpm ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                                 df        sum_sq      mean_sq          F  \
C(concentration)                3.0  13850.202190  4616.734063  32.694225
C(compound)                     1.0    412.792353   412.792353   2.923263
C(concentration):C(compound)    3.0    516.753264   172.251088   1.219827
Residual                      121.0  17086.345217   141.209465        NaN

                                    PR(>F)
C(concentration)              1.504955e-15
C(compound)                   8.987438e-02
C(concentration):C(compound)  3.055234e-01
Residual                               NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): sem efeito significativo (p = 0.0899)
C(concentration):C(compound): sem efeito significativo (p = 0.3055)

## Comprimento

In [ ]:
features = ['body_length']
compounds = {'BCT': df_BCT, 'BST': df_BST}

display(df_BCT)

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)


# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

,sample,type,concentration,bpm,body_length,yolk_sac_area,pigmented_area,open_swim_bladder,edema_present,deformation_present,aquisition_data
0,1_bct_1,BCT,1.0,115,3.721,0.396,18096,no,no,no,2025-08-18T15:35:09.206382-03:00
1,2_bct_1,BCT,1.0,133,3.933,0.432,19992,no,no,no,2025-08-18T15:41:30.4801149-03:00
2,3_bct_1,BCT,1.0,149,3.690,0.245,23613,no,no,yes,2025-08-18T15:45:05.6896737-03:00
3,4_bct_1,BCT,1.0,124,3.909,0.362,27886,no,no,no,2025-08-18T15:49:14.9293665-03:00
4,5_bct_1,BCT,1.0,124,4.302,0.501,27014,no,no,no,2025-08-18T15:56:33.7860505-03:00
...,...,...,...,...,...,...,...,...,...,...,...
90,8_control,BCT,0.0,152,3.849,0.266,11241,no,no,no,NaN
91,9_control,BCT,0.0,172,3.971,0.326,13793,yes,no,no,NaN
92,10_control,BCT,0.0,168,3.966,0.262,11152,no,no,no,NaN
93,11_control,BCT,0.0,152,3.974,0.305,12402,yes,no,yes,NaN
94,12_control,BCT,0.0,152,3.994,0.298,13940,yes,no,no,NaN

=== BCT ===

Variável: body_length

Levene p-valor (body_length) = 0.5629 -> homocedasticidade
Concentração 0.0: p = 0.0000 -> não normal
Concentração 0.5: p = 0.5278 -> distribuição normal
Concentração 1.0: p = 0.5219 -> distribuição normal
Concentração 2.0: p = 0.2586 -> distribuição normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = 28.0998, p = 0.0000

--- Dunn test (pós-hoc não paramétrico) ---
          0.0       0.5       1.0       2.0
0.0  1.000000  0.016981  1.000000  0.000004
0.5  0.016981  1.000000  1.000000  0.523865
1.0  1.000000  1.000000  1.000000  0.023123
2.0  0.000004  0.523865  0.023123  1.000000

=== BST ===

Variável: body_length

Levene p-valor (body_length) = 0.5849 -> homocedasticidade
Concentração 0.0: p = 0.0000 -> não normal
Concentração 0.5: p = 0.9007 -> distribuição normal
Concentração 1.0: p = 0.0283 -> não normal
Concentração 2.0: p = 0.7326 -> distribuição normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = 21.2091, p = 0.0001

--- Dunn test (pós-hoc não paramétrico) ---
          0.0       0.5       1.0       2.0
0.0  1.000000  1.000000  1.000000  0.000238
0.5  1.000000  1.000000  0.909622  0.000107
1.0  1.000000  0.909622  1.000000  0.032562
2.0  0.000238  0.000107  0.032562  1.000000

=== ANOVA Two-way: body_length ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                                 df    sum_sq   mean_sq          F  \
C(concentration)                3.0  3.425911  1.141970  28.753252
C(compound)                     1.0  0.050136  0.050136   1.262361
C(concentration):C(compound)    3.0  0.448608  0.149536   3.765114
Residual                      121.0  4.805662  0.039716        NaN

                                    PR(>F)
C(concentration)              4.167606e-14
C(compound)                   2.634289e-01
C(concentration):C(compound)  1.260618e-02
Residual                               NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): sem efeito significativo (p = 0.2634)
C(concentration):C(compound): efeito significativo (p = 0.0126)

## Área do Saco

In [22]:
features = ['yolk_sac_area']
compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: yolk_sac_area

Levene p-valor (yolk_sac_area) = 0.0569 -> homocedasticidade
Concentração 0.0: p = 0.9233 -> distribuição normal
Concentração 0.5: p = 0.0802 -> distribuição normal
Concentração 1.0: p = 0.9610 -> distribuição normal
Concentração 2.0: p = 0.3571 -> distribuição normal

=== ANOVA One-way (clássico) ===
                    df    sum_sq   mean_sq          F        PR(>F)
C(concentration)   3.0  0.108389  0.036130  19.997012  4.195404e-09
Residual          60.0  0.108405  0.001807        NaN           NaN

--- Tukey HSD ---
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
   0.0    0.5   0.0599 0.0008  0.0209 0.0988   True
   0.0    1.0   0.1073    0.0  0.0651 0.1494   True
   0.0    2.0   0.0712 0.0001  0.0308 0.1116   True
   0.5    1.0   0.0474 0.0733 -0.0031 0.0979  False
   0.5    2.0   0.0113 0.9285 -0.0378 0.0604  False
   1.0    2.0  -0.0361 0.2621 -0.0877 0.0155  False
---------------------------------------------------

=== BST ===

Variável: yolk_sac_area

Levene p-valor (yolk_sac_area) = 0.0364 -> heterocedasticidade
Concentração 0.0: p = 0.9233 -> distribuição normal
Concentração 0.5: p = 0.4687 -> distribuição normal
Concentração 1.0: p = 0.3466 -> distribuição normal
Concentração 2.0: p = 0.7788 -> distribuição normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1      ddof2          F     p-unc      np2
0  concentration      3  21.338843  12.308082  0.000069  0.33319

--- Games-Howell ---
     A    B   mean(A)   mean(B)      diff        se         T         df  \
0  0.0  0.5  0.264412  0.312417 -0.048005  0.009652 -4.973635  26.560407
1  0.0  1.0  0.264412  0.305100 -0.040688  0.017619 -2.309311  11.557556
2  0.0  2.0  0.264412  0.323111 -0.058699  0.011301 -5.193979  15.294584
3  0.5  1.0  0.312417  0.305100  0.007317  0.018145  0.403239  12.631321
4  0.5  2.0  0.312417  0.323111 -0.010694  0.012104 -0.883516  16.392873
5  1.0  2.0  0.305100  0.323111 -0.018011  0.019073 -0.944305  14.198541

       pval    hedges
0  0.000190 -1.412310
1  0.152249 -1.005606
2  0.000533 -1.679836
3  0.976870  0.176020
4  0.813345 -0.379470
5  0.781987 -0.402168

=== ANOVA Two-way: yolk_sac_area ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                                 df    sum_sq   mean_sq          F  \
C(concentration)                3.0  0.131594  0.043865  28.138729
C(compound)                     1.0  0.006079  0.006079   3.899604
C(concentration):C(compound)    3.0  0.016456  0.005485   3.518795
Residual                      121.0  0.188624  0.001559        NaN

                                    PR(>F)
C(concentration)              7.112128e-14
C(compound)                   5.057480e-02
C(concentration):C(compound)  1.723469e-02
Residual                               NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): sem efeito significativo (p = 0.0506)
C(concentration):C(compound): efeito significativo (p = 0.0172)

## Área Pigmentada

In [23]:
features = ['pigmented_area']
compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: pigmented_area

Levene p-valor (pigmented_area) = 0.0125 -> heterocedasticidade
Concentração 0.0: p = 0.0313 -> não normal
Concentração 0.5: p = 0.2177 -> distribuição normal
Concentração 1.0: p = 0.7354 -> distribuição normal
Concentração 2.0: p = 0.7891 -> distribuição normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = 45.5116, p = 0.0000

--- Dunn test (pós-hoc não paramétrico) ---
          0.0       0.5      1.0       2.0
0.0  1.000000  0.000068  0.00001  0.000006
0.5  0.000068  1.000000  1.00000  1.000000
1.0  0.000010  1.000000  1.00000  1.000000
2.0  0.000006  1.000000  1.00000  1.000000

=== BST ===

Variável: pigmented_area

Levene p-valor (pigmented_area) = 0.1161 -> homocedasticidade
Concentração 0.0: p = 0.0313 -> não normal
Concentração 0.5: p = 0.2475 -> distribuição normal
Concentração 1.0: p = 0.4088 -> distribuição normal
Concentração 2.0: p = 0.4879 -> distribuição normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = 44.1512, p = 0.0000

--- Dunn test (pós-hoc não paramétrico) ---
          0.0       0.5       1.0       2.0
0.0  1.000000  0.000001  0.000021  0.000427
0.5  0.000001  1.000000  1.000000  1.000000
1.0  0.000021  1.000000  1.000000  1.000000
2.0  0.000427  1.000000  1.000000  1.000000

=== ANOVA Two-way: pigmented_area ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                                 df        sum_sq       mean_sq           F  \
C(concentration)                3.0  2.741213e+09  9.137377e+08  107.307112
C(compound)                     1.0  1.307042e+06  1.307042e+06    0.153496
C(concentration):C(compound)    3.0  2.643703e+07  8.812344e+06    1.034900
Residual                      121.0  1.030335e+09  8.515164e+06         NaN

                                    PR(>F)
C(concentration)              6.078525e-34
C(compound)                   6.959059e-01
C(concentration):C(compound)  3.797345e-01
Residual                               NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): sem efeito significativo (p = 0.6959)
C(concentration):C(compound): sem efeito significativo (p = 0.3797)

# Cometa

In [24]:
df_cometa = pd.read_csv("../../bancos de dados/dataset_cometa.csv", sep=';')

df_cometa = df_cometa.rename(columns={'tail moment': 'tail_moment'})

display(df_cometa)

df_cometa['tail_moment'] = (
    df_cometa['tail_moment']
    .astype(str)                 # garante que tudo seja string
    .str.replace(',', '.', regex=False)  # troca vírgula por ponto
    .str.strip()                 # remove espaços
    .replace(['', ' ', 'nan', 'NaN', None], pd.NA)  # limpa valores inválidos
    .astype(float)               # converte para float
)

df_cometa['concentration'] = (
    df_cometa['concentration']
    .astype(str)                 # garante que tudo seja string
    .str.replace(',', '.', regex=False)  # troca vírgula por ponto
    .str.strip()                 # remove espaços
    .replace(['', ' ', 'nan', 'NaN', None], pd.NA)  # limpa valores inválidos
    .astype(float)               # converte para float
)

df_cometa.to_excel('cometa_limpo.xlsx', index=False)

df_cometa = df_cometa[df_cometa['concentration'] != 'Positive']

df_cometa

                 type concentration tail_moment
0    control_negative           0.0        0,97
1    control_negative           0.0        1,71
2    control_negative           0.0        1,08
3    control_negative           0.0        1,14
4    control_negative           0.0        1,63
..                ...           ...         ...
862  control_positive           0.0        3,45
863  control_positive           0.0       22,24
864  control_positive           0.0        2,38
865  control_positive           0.0       44,49
866  control_positive           0.0        2,29

[867 rows x 3 columns]

                 type  concentration  tail_moment
0    control_negative            0.0         0.97
1    control_negative            0.0         1.71
2    control_negative            0.0         1.08
3    control_negative            0.0         1.14
4    control_negative            0.0         1.63
..                ...            ...          ...
862  control_positive            0.0         3.45
863  control_positive            0.0        22.24
864  control_positive            0.0         2.38
865  control_positive            0.0        44.49
866  control_positive            0.0         2.29

[867 rows x 3 columns]

In [25]:
df_BCT = df_cometa[df_cometa["type"] != "BST"]
df_BST = df_cometa[df_cometa["type"] != "BCT"]

df_BCT = df_BCT.copy()
df_BST = df_BST.copy()

bct_c = []

for i in range(len(df_BCT)):
    bct_c.append('BCT')

bst_c = []

for i in range(len(df_BST)):
    bst_c.append('BST')

df_BCT['type'] = bct_c
df_BST['type'] = bst_c

display(df_BCT)

    type  concentration  tail_moment
0    BCT            0.0         0.97
1    BCT            0.0         1.71
2    BCT            0.0         1.08
3    BCT            0.0         1.14
4    BCT            0.0         1.63
..   ...            ...          ...
862  BCT            0.0         3.45
863  BCT            0.0        22.24
864  BCT            0.0         2.38
865  BCT            0.0        44.49
866  BCT            0.0         2.29

[483 rows x 3 columns]

In [26]:
features = ['tail_moment']
compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: tail_moment

Levene p-valor (tail_moment) = 0.0004 -> heterocedasticidade
Concentração 0.0: p = 0.0000 -> não normal
Concentração 0.5: p = 0.0000 -> não normal
Concentração 1.0: p = 0.0000 -> não normal
Concentração 2.0: p = 0.0000 -> não normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = 62.8095, p = 0.0000

--- Dunn test (pós-hoc não paramétrico) ---
              0.0           0.5           1.0       2.0
0.0  1.000000e+00  3.428687e-10  5.024326e-08  0.000037
0.5  3.428687e-10  1.000000e+00  1.000000e+00  0.174966
1.0  5.024326e-08  1.000000e+00  1.000000e+00  0.299206
2.0  3.720916e-05  1.749660e-01  2.992063e-01  1.000000

=== BST ===

Variável: tail_moment

Levene p-valor (tail_moment) = 0.0000 -> heterocedasticidade
Concentração 0.0: p = 0.0000 -> não normal
Concentração 0.5: p = 0.0000 -> não normal
Concentração 1.0: p = 0.0000 -> não normal
Concentração 2.0: p = 0.0000 -> não normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = 104.5676, p = 0.0000

--- Dunn test (pós-hoc não paramétrico) ---
              0.0           0.5           1.0       2.0
0.0  1.000000e+00  1.039436e-11  4.974878e-21  0.000007
0.5  1.039436e-11  1.000000e+00  5.678319e-01  0.813243
1.0  4.974878e-21  5.678319e-01  1.000000e+00  0.010178
2.0  6.506853e-06  8.132431e-01  1.017754e-02  1.000000

=== ANOVA Two-way: tail_moment ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                                  df         sum_sq      mean_sq          F  \
C(concentration)                 3.0   11792.680557  3930.893519  18.951797
C(compound)                      1.0       3.855287     3.855287   0.018587
C(concentration):C(compound)     3.0      34.729153    11.576384   0.055813
Residual                      1068.0  221519.583994   207.415341        NaN

                                    PR(>F)
C(concentration)              5.587470e-12
C(compound)                   8.915820e-01
C(concentration):C(compound)  9.826566e-01
Residual                               NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): sem efeito significativo (p = 0.8916)
C(concentration):C(compound): sem efeito significativo (p = 0.9827)

# RTqPCR

In [27]:
df = pd.read_excel("../../bancos de dados/dataset_rtqpcr.xlsx")

df_BCT = df[df["type"] != "bst"]
df_BST = df[df["type"] != "bct"]

df_BCT = df_BCT.copy()
df_BST = df_BST.copy()

bct_c = []

for i in range(len(df_BCT)):
    bct_c.append('bct')

bst_c = []

for i in range(len(df_BST)):
    bst_c.append('bst')

df_BCT['type'] = bct_c
df_BST['type'] = bst_c

display(df_BCT)

  type  concentration   nestin    gfap     il1     tnf   casp9
0  bct            0.0  0.94400  0.9550  0.9470  0.9691  0.9254
1  bct            0.0  1.00000  0.9741  1.0540  1.0318  1.0140
2  bct            0.0  1.05400  1.0740     NaN     NaN  1.0640
3  bct            0.5  0.95380  0.9920  0.4823  0.6748  1.6640
4  bct            0.5  0.75019  1.0190  0.6556  0.7795  1.5730
5  bct            0.5  0.89670  0.9890  0.5304  0.7670  1.7420

In [28]:
features = ['nestin']
compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        display(df)
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

  type  concentration   nestin    gfap     il1     tnf   casp9
0  bct            0.0  0.94400  0.9550  0.9470  0.9691  0.9254
1  bct            0.0  1.00000  0.9741  1.0540  1.0318  1.0140
2  bct            0.0  1.05400  1.0740     NaN     NaN  1.0640
3  bct            0.5  0.95380  0.9920  0.4823  0.6748  1.6640
4  bct            0.5  0.75019  1.0190  0.6556  0.7795  1.5730
5  bct            0.5  0.89670  0.9890  0.5304  0.7670  1.7420

Variável: nestin

Levene p-valor (nestin) = 0.5382 -> homocedasticidade
Concentração 0.0: p = 0.9800 -> distribuição normal
Concentração 0.5: p = 0.5258 -> distribuição normal

=== ANOVA One-way (clássico) ===
                   df    sum_sq   mean_sq         F    PR(>F)
C(concentration)  1.0  0.026309  0.026309  3.743545  0.125119
Residual          4.0  0.028112  0.007028       NaN       NaN

--- Tukey HSD ---
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
   0.0    0.5  -0.1324 0.1251 -0.3225 0.0576  False
---------------------------------------------------

=== BST ===

  type  concentration  nestin    gfap     il1       tnf   casp9
0  bst            0.0  0.9440  0.9550  0.9470  0.969100  0.9254
1  bst            0.0  1.0000  0.9741  1.0540  1.031800  1.0140
2  bst            0.0  1.0540  1.0740     NaN       NaN  1.0640
6  bst            0.5  0.8483  0.9530  0.5954  0.362714  1.4540
7  bst            0.5  0.6586  0.9940  0.4400  0.350981  1.6650
8  bst            0.5     NaN  1.0940     NaN  0.374276     NaN

Variável: nestin

Levene p-valor (nestin) = nan -> heterocedasticidade
Concentração 0.0: p = 0.9800 -> distribuição normal
Concentração 0.5: p = nan -> não normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1     ddof2        F     p-unc       np2
0  concentration      1  1.229029  6.04286  0.206869  0.751085

--- Games-Howell ---
     A    B   mean(A)  mean(B)      diff        se         T        df  \
0  0.0  0.5  0.999333  0.75345  0.245883  0.100025  2.458223  1.229029

       pval    hedges
0  0.206869  1.997498

=== ANOVA Two-way: nestin ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                               df    sum_sq   mean_sq          F    PR(>F)
C(concentration)              1.0  0.086232  0.086232  11.573560  0.011411
C(compound)                   1.0  0.006864  0.006864   0.921260  0.369116
C(concentration):C(compound)  1.0  0.008580  0.008580   1.151575  0.318814
Residual                      7.0  0.052155  0.007451        NaN       NaN
C(concentration): efeito significativo (p = 0.0114)
C(compound): sem efeito significativo (p = 0.3691)
C(concentration):C(compound): sem efeito significativo (p = 0.3188)

In [29]:
features['gfap']

compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

TypeError: list indices must be integers or slices, not str

In [30]:
features = ['il1']

compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: il1

Levene p-valor (il1) = nan -> heterocedasticidade
Concentração 0.0: p = nan -> não normal
Concentração 0.5: p = 0.5198 -> distribuição normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1     ddof2          F     p-unc       np2
0  concentration      1  2.602466  35.711991  0.013873  0.916004

--- Games-Howell ---
     A    B  mean(A)  mean(B)    diff        se         T        df      pval  \
0  0.0  0.5   1.0005   0.5561  0.4444  0.074365  5.975951  2.602466  0.013873

     hedges
0  3.797391

=== BST ===

Variável: il1

Levene p-valor (il1) = nan -> heterocedasticidade
Concentração 0.0: p = nan -> não normal
Concentração 0.5: p = nan -> não normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1     ddof2          F     p-unc       np2
0  concentration      1  1.774181  26.191898  0.046024  0.929058

--- Games-Howell ---
     A    B  mean(A)  mean(B)    diff        se         T        df      pval  \
0  0.0  0.5   1.0005   0.5177  0.4828  0.094337  5.117802  1.774181  0.046024

     hedges
0  2.924458

=== ANOVA Two-way: il1 ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                               df    sum_sq   mean_sq          F    PR(>F)
C(concentration)              1.0  0.469732  0.469732  59.413440  0.000587
C(compound)                   1.0  0.000965  0.000965   0.122078  0.741026
C(concentration):C(compound)  1.0  0.000804  0.000804   0.101732  0.762655
Residual                      5.0  0.039531  0.007906        NaN       NaN
C(concentration): efeito significativo (p = 0.0006)
C(compound): sem efeito significativo (p = 0.7410)
C(concentration):C(compound): sem efeito significativo (p = 0.7627)

In [31]:
features = ['tnf']

compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: tnf

Levene p-valor (tnf) = nan -> heterocedasticidade
Concentração 0.0: p = nan -> não normal
Concentração 0.5: p = 0.2092 -> distribuição normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1    ddof2          F     p-unc       np2
0  concentration      1  2.75421  32.617435  0.013386  0.905112

--- Games-Howell ---
     A    B  mean(A)   mean(B)      diff        se         T       df  \
0  0.0  0.5  1.00045  0.740433  0.260017  0.045528  5.711168  2.75421

       pval    hedges
0  0.013386  3.551505

=== BST ===

Variável: tnf

Levene p-valor (tnf) = nan -> heterocedasticidade
Concentração 0.0: p = nan -> não normal
Concentração 0.5: p = 0.9919 -> distribuição normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1     ddof2           F     p-unc       np2
0  concentration      1  1.092985  395.683085  0.024719  0.995438

--- Games-Howell ---
     A    B  mean(A)   mean(B)      diff        se          T        df  \
0  0.0  0.5  1.00045  0.362657  0.637793  0.032063  19.891784  1.092985

       pval     hedges
0  0.024719  16.986613

=== ANOVA Two-way: tnf ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                               df    sum_sq   mean_sq           F    PR(>F)
C(concentration)              1.0  0.483637  0.483637  270.129338  0.000003
C(compound)                   1.0  0.128443  0.128443   71.740426  0.000148
C(concentration):C(compound)  1.0  0.085629  0.085629   47.826951  0.000452
Residual                      6.0  0.010742  0.001790         NaN       NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): efeito significativo (p = 0.0001)
C(concentration):C(compound): efeito significativo (p = 0.0005)

In [32]:
features = ['casp9']

compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: casp9

Levene p-valor (casp9) = 0.8043 -> homocedasticidade
Concentração 0.0: p = 0.6955 -> distribuição normal
Concentração 0.5: p = 0.9152 -> distribuição normal

=== ANOVA One-way (clássico) ===
                   df    sum_sq   mean_sq           F    PR(>F)
C(concentration)  1.0  0.650499  0.650499  107.689752  0.000487
Residual          4.0  0.024162  0.006040         NaN       NaN

--- Tukey HSD ---
Multiple Comparison of Means - Tukey HSD, FWER=0.05
==================================================
group1 group2 meandiff p-adj  lower  upper  reject
--------------------------------------------------
   0.0    0.5   0.6585 0.0005 0.4823 0.8347   True
--------------------------------------------------

=== BST ===

Variável: casp9

Levene p-valor (casp9) = nan -> heterocedasticidade
Concentração 0.0: p = 0.6955 -> distribuição normal
Concentração 0.5: p = nan -> não normal

=== Welch ANOVA (heterocedasticidade) ===
          Source  ddof1     ddof2          F     p-unc       np2
0  concentration      1  1.302681  24.409796  0.084618  0.920949

--- Games-Howell ---
     A    B   mean(A)  mean(B)      diff        se         T        df  \
0  0.0  0.5  1.001133   1.5595 -0.558367  0.113015 -4.940627  1.302681

       pval    hedges
0  0.084618 -3.924926

=== ANOVA Two-way: casp9 ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                               df    sum_sq   mean_sq           F    PR(>F)
C(concentration)              1.0  1.043185  1.043185  129.759057  0.000009
C(compound)                   1.0  0.005351  0.005351    0.665613  0.441459
C(concentration):C(compound)  1.0  0.006689  0.006689    0.832016  0.392020
Residual                      7.0  0.056276  0.008039         NaN       NaN
C(concentration): efeito significativo (p = 0.0000)
C(compound): sem efeito significativo (p = 0.4415)
C(concentration):C(compound): sem efeito significativo (p = 0.3920)

# ROS

In [33]:
df = pd.read_excel("../../bancos de dados/dataset_ros_geral.xlsx")

df_BCT = df[df["type"] != "BST"]
df_BST = df[df["type"] != "BCT"]

df_BCT = df_BCT.copy()
df_BST = df_BST.copy()

bct_c = []

for i in range(len(df_BCT)):
    bct_c.append('BCT')

bst_c = []

for i in range(len(df_BST)):
    bst_c.append('BST')

df_BCT['type'] = bct_c
df_BST['type'] = bst_c

display(df_BCT)
display(df_BST)

,sample,type,concentration,intensity,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Snap-13,BCT,0.0,27157.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Snap-15,BCT,0.0,17222.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Snap-17,BCT,0.0,19979.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Snap-19,BCT,0.0,NaN,NaN,220784.0,NaN,NaN,média,desvio padrão
4,Snap-22,BCT,0.0,22546.0,NaN,NaN,NaN,control,22125.375,6344.075795
5,Snap-24,BCT,0.0,32644.0,NaN,NaN,NaN,BCT 0.5,51093.666667,36678.923171
6,Snap-26,BCT,0.0,25226.0,NaN,NaN,NaN,BST 0.5,52405.111111,31005.159314
7,Snap-28,BCT,0.0,11927.0,NaN,NaN,NaN,BCT 1,66658.666667,49988.023795
8,Snap-30,BCT,0.0,20302.0,NaN,NaN,NaN,BST 1,95389.222222,65785.86666
9,Snap-181-Image Export-02.tif,BCT,0.5,20526.0,31828.0,NaN,NaN,BCT 2,65720.909091,47895.153962
10,Snap-183-Image Export-03.tif,BCT,0.5,13584.0,35439.0,NaN,NaN,BST 2,87392.357143,74136.10043
11,Snap-186-Image Export-04.tif,BCT,0.5,98181.0,173923.0,NaN,NaN,NaN,NaN,NaN
12,Snap-189-Image Export-05.tif,BCT,0.5,80403.0,158129.0,NaN,NaN,NaN,NaN,NaN
13,Snap-192-Image Export-06.tif,BCT,0.5,17428.0,33419.0,NaN,NaN,NaN,NaN,NaN
14,Snap-194-Image Export-07.tif,BCT,0.5,106681.0,177939.0,NaN,NaN,NaN,NaN,NaN
15,Snap-196-Image Export-08.tif,BCT,0.5,62203.0,154595.0,NaN,NaN,NaN,NaN,NaN
16,Snap-197-Image Export-09.tif,BCT,0.5,NaN,218891.0,140658.0,NaN,NaN,NaN,NaN
17,Snap-198-Image Export-10.tif,BCT,0.5,38888.0,56590.0,NaN,NaN,controle2,123087.4,84140.423028
18,Snap-200-Image Export-12.tif,BCT,0.5,21949.0,43278.0,NaN,NaN,BCT 0.5,51093.666667,36678.923171
29,Snap-108,BCT,1.0,182270.0,NaN,NaN,NaN,NaN,NaN,NaN
30,Snap-112,BCT,1.0,85052.0,NaN,NaN,NaN,NaN,NaN,NaN
31,Snap-113,BCT,1.0,32773.0,NaN,NaN,NaN,NaN,NaN,NaN
32,Snap-116,BCT,1.0,36732.0,NaN,NaN,NaN,NaN,NaN,NaN
33,Snap-117,BCT,1.0,23044.0,NaN,NaN,NaN,NaN,NaN,NaN
34,Snap-122,BCT,1.0,73870.0,NaN,NaN,NaN,NaN,NaN,NaN
35,Snap-123,BCT,1.0,43501.0,NaN,NaN,NaN,NaN,NaN,NaN
36,Snap-126,BCT,1.0,43891.0,NaN,NaN,NaN,NaN,NaN,NaN
37,Snap-127,BCT,1.0,65865.0,NaN,NaN,NaN,NaN,NaN,NaN
38,Snap-130,BCT,1.0,26871.0,NaN,NaN,NaN,NaN,NaN,NaN
39,Snap-131,BCT,1.0,39368.0,NaN,NaN,NaN,NaN,NaN,NaN
40,Snap-134,BCT,1.0,146667.0,NaN,NaN,NaN,NaN,NaN,NaN
50,Snap-53,BCT,2.0,161408.0,NaN,NaN,NaN,NaN,NaN,NaN
51,Snap-58,BCT,2.0,94274.0,NaN,NaN,NaN,NaN,NaN,NaN
52,Snap-59,BCT,2.0,27912.0,NaN,NaN,NaN,NaN,NaN,NaN
53,Snap-63,BCT,2.0,137639.0,NaN,NaN,NaN,NaN,NaN,NaN
54,Snap-64,BCT,2.0,34900.0,NaN,NaN,NaN,NaN,NaN,NaN
55,Snap-67,BCT,2.0,17478.0,NaN,NaN,NaN,NaN,NaN,NaN
56,Snap-68,BCT,2.0,37922.0,NaN,NaN,NaN,NaN,NaN,NaN
57,Snap-71,BCT,2.0,42094.0,NaN,NaN,NaN,NaN,NaN,NaN
58,Snap-73,BCT,2.0,87993.0,NaN,NaN,NaN,NaN,NaN,NaN
59,Snap-74,BCT,2.0,39001.0,NaN,NaN,NaN,NaN,NaN,NaN
60,Snap-77,BCT,2.0,42309.0,NaN,NaN,NaN,NaN,NaN,NaN

,sample,type,concentration,intensity,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Snap-13,BST,0.0,27157.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Snap-15,BST,0.0,17222.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Snap-17,BST,0.0,19979.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Snap-19,BST,0.0,NaN,NaN,220784.0,NaN,NaN,média,desvio padrão
4,Snap-22,BST,0.0,22546.0,NaN,NaN,NaN,control,22125.375,6344.075795
5,Snap-24,BST,0.0,32644.0,NaN,NaN,NaN,BCT 0.5,51093.666667,36678.923171
6,Snap-26,BST,0.0,25226.0,NaN,NaN,NaN,BST 0.5,52405.111111,31005.159314
7,Snap-28,BST,0.0,11927.0,NaN,NaN,NaN,BCT 1,66658.666667,49988.023795
8,Snap-30,BST,0.0,20302.0,NaN,NaN,NaN,BST 1,95389.222222,65785.86666
19,Snap-167-Image Export-16.tif,BST,0.5,56845.0,77172.0,NaN,NaN,BST 0.5,52405.111111,31005.159314
20,Snap-168-Image Export-17.tif,BST,0.5,26746.0,46790.0,NaN,NaN,NaN,NaN,NaN
21,Snap-169-Image Export-18.tif,BST,0.5,52486.0,66913.0,NaN,NaN,controle x,181285.7,117368.530383
22,Snap-170-Image Export-19.tif,BST,0.5,53898.0,67249.0,NaN,NaN,BCT 0.5 x,108403.1,74295.228313
23,Snap-171-Image Export-20.tif,BST,0.5,22707.0,38009.0,NaN,NaN,BST 0.5 x,99270.4,79351.589403
24,Snap-172-Image Export-21.tif,BST,0.5,103288.0,194615.0,NaN,NaN,NaN,NaN,NaN
25,Snap-174-Image Export-22.tif,BST,0.5,NaN,281323.0,192070.0,NaN,NaN,NaN,NaN
26,Snap-176-Image Export-23.tif,BST,0.5,95866.0,117833.0,NaN,NaN,NaN,NaN,NaN
27,Snap-178-Image Export-24.tif,BST,0.5,12047.0,36555.0,NaN,NaN,NaN,NaN,NaN
28,Snap-179-Image Export-25.tif,BST,0.5,47763.0,66245.0,NaN,NaN,NaN,NaN,NaN
41,Snap-102,BST,1.0,129003.0,NaN,NaN,NaN,NaN,NaN,NaN
42,Snap-106,BST,1.0,28424.0,NaN,NaN,NaN,NaN,NaN,NaN
43,Snap-80,BST,1.0,144632.0,NaN,NaN,NaN,NaN,NaN,NaN
44,Snap-84,BST,1.0,195944.0,NaN,NaN,NaN,NaN,NaN,NaN
45,Snap-85,BST,1.0,119639.0,NaN,NaN,NaN,NaN,NaN,NaN
46,Snap-89,BST,1.0,148786.0,NaN,NaN,NaN,NaN,NaN,NaN
47,Snap-93,BST,1.0,45706.0,NaN,NaN,NaN,NaN,NaN,NaN
48,Snap-97,BST,1.0,14903.0,NaN,NaN,NaN,NaN,NaN,NaN
49,Snap-99,BST,1.0,31466.0,NaN,NaN,NaN,NaN,NaN,NaN
61,Snap-06,BST,2.0,138756.0,NaN,NaN,NaN,NaN,NaN,NaN
62,Snap-07,BST,2.0,227388.0,NaN,NaN,NaN,NaN,NaN,NaN
63,Snap-08,BST,2.0,81622.0,NaN,NaN,NaN,NaN,NaN,NaN
64,Snap-10,BST,2.0,221833.0,NaN,NaN,NaN,NaN,NaN,NaN
65,Snap-33,BST,2.0,34780.0,NaN,NaN,NaN,NaN,NaN,NaN
66,Snap-34,BST,2.0,34060.0,NaN,NaN,NaN,NaN,NaN,NaN
67,Snap-36,BST,2.0,30409.0,NaN,NaN,NaN,NaN,NaN,NaN
68,Snap-37,BST,2.0,21443.0,NaN,NaN,NaN,NaN,NaN,NaN
69,Snap-41,BST,2.0,57522.0,NaN,NaN,NaN,NaN,NaN,NaN
70,Snap-42,BST,2.0,30228.0,NaN,NaN,NaN,NaN,NaN,NaN
71,Snap-44,BST,2.0,59028.0,NaN,NaN,NaN,NaN,NaN,NaN
72,Snap-47,BST,2.0,183982.0,NaN,NaN,NaN,NaN,NaN,NaN
73,Snap-49,BST,2.0,29019.0,NaN,NaN,NaN,NaN,NaN,NaN
74,Snap-52,BST,2.0,73423.0,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
features = ['intensity']

compounds = {'BCT': df_BCT, 'BST': df_BST}

# rodar testes individuais por composto
for compound_name, df in compounds.items():
    print(f"\n=== {compound_name} ===")
    for feature in features:
        print(f"\nVariável: {feature}")
        print()

        # testes de pré-condição
        homoced = run_levene(df, feature)
        normal = run_shapiro(df, feature)

        # ANOVA adequada
        method = run_anova_oneway(df, feature, normal=normal, homoced=homoced)

        # Pós-teste adequado
        run_posthoc(df, feature, method=method)

# rodar two-way ANOVA com todos os compostos juntos
df_all = pd.concat([df_BCT.assign(compound='BCT'),
                    df_BST.assign(compound='BST')],
                   ignore_index=True)

for feature in features:
    print(f"\n=== ANOVA Two-way: {feature} ===")
    run_anova_twoway(df_all, feature)

=== BCT ===

Variável: intensity

Levene p-valor (intensity) = nan -> heterocedasticidade
Concentração 0.0: p = nan -> não normal
Concentração 0.5: p = nan -> não normal
Concentração 1.0: p = 0.0078 -> não normal
Concentração 2.0: p = 0.0219 -> não normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = nan, p = nan

--- Dunn test (pós-hoc não paramétrico) ---
          0.0       0.5       1.0       2.0
0.0  1.000000  0.434616  0.016263  0.028389
0.5  0.434616  1.000000  1.000000  1.000000
1.0  0.016263  1.000000  1.000000  1.000000
2.0  0.028389  1.000000  1.000000  1.000000

=== BST ===

Variável: intensity

Levene p-valor (intensity) = nan -> heterocedasticidade
Concentração 0.0: p = nan -> não normal
Concentração 0.5: p = nan -> não normal
Concentração 1.0: p = 0.2202 -> distribuição normal
Concentração 2.0: p = 0.0042 -> não normal

=== Kruskal-Wallis (não paramétrico) ===
estatística = nan, p = nan

--- Dunn test (pós-hoc não paramétrico) ---
          0.0       0.5       1.0       2.0
0.0  1.000000  0.301991  0.021843  0.010144
0.5  0.301991  1.000000  1.000000  1.000000
1.0  0.021843  1.000000  1.000000  1.000000
2.0  0.010144  1.000000  1.000000  1.000000

=== ANOVA Two-way: intensity ===

=== Two-way ANOVA (clássico, assumir normalidade/homocedasticidade) ===
                                df        sum_sq       mean_sq         F  \
C(concentration)               3.0  3.960534e+10  1.320178e+10  5.415640
C(compound)                    1.0  4.163937e+09  4.163937e+09  1.708132
C(concentration):C(compound)   3.0  2.982001e+09  9.940004e+08  0.407759
Residual                      72.0  1.755154e+11  2.437714e+09       NaN

                                PR(>F)
C(concentration)              0.002044
C(compound)                   0.195387
C(concentration):C(compound)  0.747885
Residual                           NaN
C(concentration): efeito significativo (p = 0.0020)
C(compound): sem efeito significativo (p = 0.1954)
C(concentration):C(compound): sem efeito significativo (p = 0.7479)