# Developmental, morphological, cardiac, and pigmentation endpoints

This notebook generates the final article figures for body length, swim-bladder inflation, edema, deformation, heart rate, and normalized pigmented area. Raw labels are preserved, then BCT is displayed as SCB and BST as SCF.

## Legacy-analysis record

The source workbook is `article/data/processed/zebrafish_endpoints.xlsx`, copied from `Ensaios Zebrafish/premium/dataset_zebrafish.xlsx`. The legacy statistical source is the root-level `estatistica.ipynb`. Body length used Kruskal–Wallis followed by Dunn; heart rate used one-way ANOVA followed by Tukey. The old pigmentation test used raw pigmented area, so it cannot support the normalized plot and is recalculated here on pigmented area divided by body length. Binary endpoints are evaluated with two-sided Fisher exact tests against the shared control and Holm correction. All displayed stars are generated from adjusted p-values and saved to `data/processed/developmental_endpoint_statistics.csv`.

In [1]:
# The implementation is kept in a plain Python module so the same audited code can
# be run from Jupyter or non-interactively during manuscript builds.
%run ../scripts/plot_developmental_endpoints.py

                     figure         comparison                             test   p_adjusted symbol
                body_length SCB 0.5 vs Control Kruskal-Wallis + Dunn-Bonferroni 2.652501e-02      *
                body_length SCB 1.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.000000e+00     ns
                body_length SCB 2.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 3.080397e-05   ****
                body_length SCF 0.5 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.000000e+00     ns
                body_length SCF 1.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.000000e+00     ns
                body_length SCF 2.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.120927e-05   ****
              yolk_sac_area SCB 0.5 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.456037e-03     **
              yolk_sac_area SCB 1.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 7.843915e-06   ****
              yolk_sac_area SCB 2.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.169466e-04    ***
              yolk_sac_area SCF 0.5 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.245795e-02      *
              yolk_sac_area SCF 1.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.414838e-01     ns
              yolk_sac_area SCF 2.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 4.858983e-03     **
developmental_abnormalities SCB 0.5 vs Control              Fisher exact + Holm 4.907418e-02      *
developmental_abnormalities SCB 1.0 vs Control              Fisher exact + Holm 5.066932e-02     ns
developmental_abnormalities SCB 2.0 vs Control              Fisher exact + Holm 4.907418e-02      *
developmental_abnormalities SCF 0.5 vs Control              Fisher exact + Holm 1.631471e-01     ns
developmental_abnormalities SCF 1.0 vs Control              Fisher exact + Holm 4.907418e-02      *
developmental_abnormalities SCF 2.0 vs Control              Fisher exact + Holm 5.066932e-02     ns
developmental_abnormalities SCB 0.5 vs Control              Fisher exact + Holm 1.196013e-01     ns
developmental_abnormalities SCB 1.0 vs Control              Fisher exact + Holm 1.196013e-01     ns
developmental_abnormalities SCB 2.0 vs Control              Fisher exact + Holm 8.463453e-08   ****
developmental_abnormalities SCF 0.5 vs Control              Fisher exact + Holm 1.000000e+00     ns
developmental_abnormalities SCF 1.0 vs Control              Fisher exact + Holm 3.624283e-02      *
developmental_abnormalities SCF 2.0 vs Control              Fisher exact + Holm 5.585879e-06   ****
developmental_abnormalities SCB 0.5 vs Control              Fisher exact + Holm 2.945893e-02      *
developmental_abnormalities SCB 1.0 vs Control              Fisher exact + Holm 2.931436e-01     ns
developmental_abnormalities SCB 2.0 vs Control              Fisher exact + Holm 4.524119e-05   ****
developmental_abnormalities SCF 0.5 vs Control              Fisher exact + Holm 3.553676e-01     ns
developmental_abnormalities SCF 1.0 vs Control              Fisher exact + Holm 1.924397e-01     ns
developmental_abnormalities SCF 2.0 vs Control              Fisher exact + Holm 7.607435e-06   ****
                 heart_rate SCB 0.5 vs Control        One-way ANOVA + Tukey HSD 0.000000e+00   ****
                 heart_rate SCB 1.0 vs Control        One-way ANOVA + Tukey HSD 1.000000e-04    ***
                 heart_rate SCB 2.0 vs Control        One-way ANOVA + Tukey HSD 0.000000e+00   ****
                 heart_rate SCF 0.5 vs Control        One-way ANOVA + Tukey HSD 2.100000e-03     **
                 heart_rate SCF 1.0 vs Control        One-way ANOVA + Tukey HSD 3.350000e-02      *
                 heart_rate SCF 2.0 vs Control        One-way ANOVA + Tukey HSD 4.000000e-04    ***
  pigmented_area_normalized SCB 0.5 vs Control Kruskal-Wallis + Dunn-Bonferroni 2.100126e-04    ***
  pigmented_area_normalized SCB 1.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 3.409835e-05   ****
  pigmented_area_normalized SCB 2.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 1.029877e-07   ****
  pigmented_area_normalized SCF 0.5 vs Control Kruskal-Wallis + Dunn-Bonferroni 2.280465e-05   ****
  pigmented_area_normalized SCF 1.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 5.696474e-05   ****
  pigmented_area_normalized SCF 2.0 vs Control Kruskal-Wallis + Dunn-Bonferroni 7.320171e-07   ****

In [2]:
statistics = pd.read_csv(TABLES / 'developmental_endpoint_statistics.csv')
statistics

,figure,endpoint,test,omnibus_p,comparison,p_raw,p_adjusted,symbol,exposed_positive,exposed_total,control_positive,control_total
0,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCB 0.5 vs Control,4.420836e-03,2.652501e-02,*,NaN,NaN,NaN,NaN
1,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCB 1.0 vs Control,2.594553e-01,1.000000e+00,ns,NaN,NaN,NaN,NaN
2,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCB 2.0 vs Control,5.133995e-06,3.080397e-05,****,NaN,NaN,NaN,NaN
3,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCF 0.5 vs Control,3.339473e-01,1.000000e+00,ns,NaN,NaN,NaN,NaN
4,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCF 1.0 vs Control,4.951625e-01,1.000000e+00,ns,NaN,NaN,NaN,NaN
5,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCF 2.0 vs Control,1.868212e-06,1.120927e-05,****,NaN,NaN,NaN,NaN
6,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCB 0.5 vs Control,2.426728e-04,1.456037e-03,**,NaN,NaN,NaN,NaN
7,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCB 1.0 vs Control,1.307319e-06,7.843915e-06,****,NaN,NaN,NaN,NaN
8,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCB 2.0 vs Control,1.949110e-05,1.169466e-04,***,NaN,NaN,NaN,NaN
9,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCF 0.5 vs Control,2.076325e-03,1.245795e-02,*,NaN,NaN,NaN,NaN
10,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCF 1.0 vs Control,2.358063e-02,1.414838e-01,ns,NaN,NaN,NaN,NaN
11,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCF 2.0 vs Control,8.098306e-04,4.858983e-03,**,NaN,NaN,NaN,NaN
12,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCB 0.5 vs Control,8.179030e-03,4.907418e-02,*,0.0,11.0,15.0,34.0
13,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCB 1.0 vs Control,1.688977e-02,5.066932e-02,ns,0.0,9.0,15.0,34.0
14,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCB 2.0 vs Control,9.185171e-03,4.907418e-02,*,0.0,10.0,15.0,34.0
15,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCF 0.5 vs Control,1.631471e-01,1.631471e-01,ns,2.0,12.0,15.0,34.0
16,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCF 1.0 vs Control,9.185171e-03,4.907418e-02,*,0.0,10.0,15.0,34.0
17,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCF 2.0 vs Control,1.688977e-02,5.066932e-02,ns,0.0,9.0,15.0,34.0
18,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCB 0.5 vs Control,5.555556e-02,1.196013e-01,ns,2.0,11.0,0.0,34.0
19,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCB 1.0 vs Control,3.986711e-02,1.196013e-01,ns,2.0,9.0,0.0,34.0
20,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCB 2.0 vs Control,1.410575e-08,8.463453e-08,****,9.0,10.0,0.0,34.0
21,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCF 0.5 vs Control,1.000000e+00,1.000000e+00,ns,0.0,12.0,0.0,34.0
22,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCF 1.0 vs Control,9.060707e-03,3.624283e-02,*,3.0,10.0,0.0,34.0
23,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCF 2.0 vs Control,1.117176e-06,5.585879e-06,****,7.0,9.0,0.0,34.0
24,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCB 0.5 vs Control,7.364733e-03,2.945893e-02,*,6.0,11.0,4.0,34.0
25,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCB 1.0 vs Control,1.465718e-01,2.931436e-01,ns,3.0,9.0,4.0,34.0
26,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCB 2.0 vs Control,9.048237e-06,4.524119e-05,****,9.0,10.0,4.0,34.0
27,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCF 0.5 vs Control,3.553676e-01,3.553676e-01,ns,3.0,12.0,4.0,34.0
28,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCF 1.0 vs Control,6.414656e-02,1.924397e-01,ns,4.0,10.0,4.0,34.0
29,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCF 2.0 vs Control,1.267906e-06,7.607435e-06,****,9.0,9.0,4.0,34.0
30,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCB 0.5 vs Control,NaN,0.000000e+00,****,NaN,NaN,NaN,NaN
31,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCB 1.0 vs Control,NaN,1.000000e-04,***,NaN,NaN,NaN,NaN
32,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCB 2.0 vs Control,NaN,0.000000e+00,****,NaN,NaN,NaN,NaN
33,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCF 0.5 vs Control,NaN,2.100000e-03,**,NaN,NaN,NaN,NaN
34,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCF 1.0 vs Control,NaN,3.350000e-02,*,NaN,NaN,NaN,NaN
35,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCF 2.0 vs Control,NaN,4.000000e-04,***,NaN,NaN,NaN,NaN
36,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCB 0.5 vs Control,3.500211e-05,2.100126e-04,***,NaN,NaN,NaN,NaN
37,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCB 1.0 vs Control,5.683058e-06,3.409835e-05,****,NaN,NaN,NaN,NaN
38,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCB 2.0 vs Control,1.716461e-08,1.029877e-07,****,NaN,NaN,NaN,NaN
39,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCF 0.5 vs Control,3.800775e-06,2.280465e-05,****,NaN,NaN,NaN,NaN
40,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCF 1.0 vs Control,9.494124e-06,5.696474e-05,****,NaN,NaN,NaN,NaN
41,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCF 2.0 vs Control,1.220029e-07,7.320171e-07,****,NaN,NaN,NaN,NaN

In [3]:
pd.read_csv(TABLES / 'developmental_endpoint_statistics.csv')

,figure,endpoint,test,omnibus_p,comparison,p_raw,p_adjusted,symbol,exposed_positive,exposed_total,control_positive,control_total
0,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCB 0.5 vs Control,4.420836e-03,2.652501e-02,*,NaN,NaN,NaN,NaN
1,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCB 1.0 vs Control,2.594553e-01,1.000000e+00,ns,NaN,NaN,NaN,NaN
2,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCB 2.0 vs Control,5.133995e-06,3.080397e-05,****,NaN,NaN,NaN,NaN
3,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCF 0.5 vs Control,3.339473e-01,1.000000e+00,ns,NaN,NaN,NaN,NaN
4,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCF 1.0 vs Control,4.951625e-01,1.000000e+00,ns,NaN,NaN,NaN,NaN
5,body_length,body_length,Kruskal-Wallis + Dunn-Bonferroni,1.269227e-08,SCF 2.0 vs Control,1.868212e-06,1.120927e-05,****,NaN,NaN,NaN,NaN
6,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCB 0.5 vs Control,2.426728e-04,1.456037e-03,**,NaN,NaN,NaN,NaN
7,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCB 1.0 vs Control,1.307319e-06,7.843915e-06,****,NaN,NaN,NaN,NaN
8,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCB 2.0 vs Control,1.949110e-05,1.169466e-04,***,NaN,NaN,NaN,NaN
9,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCF 0.5 vs Control,2.076325e-03,1.245795e-02,*,NaN,NaN,NaN,NaN
10,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCF 1.0 vs Control,2.358063e-02,1.414838e-01,ns,NaN,NaN,NaN,NaN
11,yolk_sac_area,yolk_sac_area,Kruskal-Wallis + Dunn-Bonferroni,2.421061e-07,SCF 2.0 vs Control,8.098306e-04,4.858983e-03,**,NaN,NaN,NaN,NaN
12,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCB 0.5 vs Control,8.179030e-03,4.907418e-02,*,0.0,11.0,15.0,34.0
13,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCB 1.0 vs Control,1.688977e-02,5.066932e-02,ns,0.0,9.0,15.0,34.0
14,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCB 2.0 vs Control,9.185171e-03,4.907418e-02,*,0.0,10.0,15.0,34.0
15,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCF 0.5 vs Control,1.631471e-01,1.631471e-01,ns,2.0,12.0,15.0,34.0
16,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCF 1.0 vs Control,9.185171e-03,4.907418e-02,*,0.0,10.0,15.0,34.0
17,developmental_abnormalities,open_swim_bladder,Fisher exact + Holm,NaN,SCF 2.0 vs Control,1.688977e-02,5.066932e-02,ns,0.0,9.0,15.0,34.0
18,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCB 0.5 vs Control,5.555556e-02,1.196013e-01,ns,2.0,11.0,0.0,34.0
19,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCB 1.0 vs Control,3.986711e-02,1.196013e-01,ns,2.0,9.0,0.0,34.0
20,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCB 2.0 vs Control,1.410575e-08,8.463453e-08,****,9.0,10.0,0.0,34.0
21,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCF 0.5 vs Control,1.000000e+00,1.000000e+00,ns,0.0,12.0,0.0,34.0
22,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCF 1.0 vs Control,9.060707e-03,3.624283e-02,*,3.0,10.0,0.0,34.0
23,developmental_abnormalities,edema_present,Fisher exact + Holm,NaN,SCF 2.0 vs Control,1.117176e-06,5.585879e-06,****,7.0,9.0,0.0,34.0
24,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCB 0.5 vs Control,7.364733e-03,2.945893e-02,*,6.0,11.0,4.0,34.0
25,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCB 1.0 vs Control,1.465718e-01,2.931436e-01,ns,3.0,9.0,4.0,34.0
26,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCB 2.0 vs Control,9.048237e-06,4.524119e-05,****,9.0,10.0,4.0,34.0
27,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCF 0.5 vs Control,3.553676e-01,3.553676e-01,ns,3.0,12.0,4.0,34.0
28,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCF 1.0 vs Control,6.414656e-02,1.924397e-01,ns,4.0,10.0,4.0,34.0
29,developmental_abnormalities,deformation_present,Fisher exact + Holm,NaN,SCF 2.0 vs Control,1.267906e-06,7.607435e-06,****,9.0,9.0,4.0,34.0
30,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCB 0.5 vs Control,NaN,0.000000e+00,****,NaN,NaN,NaN,NaN
31,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCB 1.0 vs Control,NaN,1.000000e-04,***,NaN,NaN,NaN,NaN
32,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCB 2.0 vs Control,NaN,0.000000e+00,****,NaN,NaN,NaN,NaN
33,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCF 0.5 vs Control,NaN,2.100000e-03,**,NaN,NaN,NaN,NaN
34,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCF 1.0 vs Control,NaN,3.350000e-02,*,NaN,NaN,NaN,NaN
35,heart_rate,bpm,One-way ANOVA + Tukey HSD,NaN,SCF 2.0 vs Control,NaN,4.000000e-04,***,NaN,NaN,NaN,NaN
36,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCB 0.5 vs Control,3.500211e-05,2.100126e-04,***,NaN,NaN,NaN,NaN
37,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCB 1.0 vs Control,5.683058e-06,3.409835e-05,****,NaN,NaN,NaN,NaN
38,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCB 2.0 vs Control,1.716461e-08,1.029877e-07,****,NaN,NaN,NaN,NaN
39,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCF 0.5 vs Control,3.800775e-06,2.280465e-05,****,NaN,NaN,NaN,NaN
40,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCF 1.0 vs Control,9.494124e-06,5.696474e-05,****,NaN,NaN,NaN,NaN
41,pigmented_area_normalized,pigmented_area_normalized,Kruskal-Wallis + Dunn-Bonferroni,2.517531e-12,SCF 2.0 vs Control,1.220029e-07,7.320171e-07,****,NaN,NaN,NaN,NaN

## Final-figure policy

Continuous endpoints are boxplots with individual observations. Binary endpoints show percentages and Wilson 95% confidence intervals. PDF is the article's vector source; matching PNG files are exported at 600 dpi. The manually assembled pigmentation montage remains separate from quantitative plotting.